// Layer 3 Tool — Render Test Strategy to Markdown. Deterministic.

export function renderMarkdown(strategy, issue) {
  const timestamp = new Date().toISOString();

  return `# Test Strategy: ${issue.key} — ${issue.summary}

> **Generated:** ${timestamp}
> **Model:** openai/gpt-oss-120b
> **Jira Type:** ${issue.issueType}

---

## Objective

${strategy.objective || 'TBD'}

## Scope

### In Scope

${strategy.inScope || 'TBD'}

### Out of Scope

${strategy.outOfScope || 'TBD'}

## Focus Areas

${strategy.focusAreas || 'TBD'}

## Approach

${strategy.approach || 'TBD'}

## Deliverables

${strategy.deliverables || 'TBD'}

## Team & Schedule

${strategy.teamAndSchedule || 'TBD'}

## Entry & Exit Criteria

${strategy.entryExitCriteria || 'TBD'}

## Risks

${strategy.risks || 'TBD'}

---

*Generated by Test Strategy Generator for Jira IDs*
*Ticket: ${issue.key}*
*Summary: ${issue.summary}*
`;
}

export function downloadMarkdown(markdown, filename) {
  const blob = new Blob([markdown], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename || 'test-strategy.md';
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
